"""add hashed_password to users

Revision ID: a523c6c1c99f
Revises: ac3f610f7888
Create Date: 2026-04-04 02:10:18.818570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a523c6c1c99f'
down_revision: Union[str, Sequence[str], None] = 'ac3f610f7888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
     # 1. add column (nullable)
    op.add_column(
        'users',
        sa.Column('hashed_password', sa.String(length=255), nullable=True)
    )

    # 2. fill data
    op.execute(
        "UPDATE users SET hashed_password = 'temp_hash'"
    )

    # 3. enforce constraint
    op.alter_column(
        'users',
        'hashed_password',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
