"""add top_transfers to reports

Revision ID: e40ee9e2c502
Revises: b311f77225af
Create Date: 2026-06-14 14:37:51.171814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e40ee9e2c502'
down_revision: Union[str, Sequence[str], None] = 'b311f77225af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Report', sa.Column('top_transfers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Report', 'top_transfers')
    # ### end Alembic commands ###
